language: node_js
services:
- docker
os:
- linux
node_js:
- node
env:
- GLOBAL_INSTALL_FLAG=--global
- GLOBAL_INSTALL_FLAG=
install:
- npm install $GLOBAL_INSTALL_FLAG
deploy:
  - provider: script
    script:
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - docker pull magland/mldevel_publish
      - docker run -v $PWD/.npmrc:/root/.npmrc -v $PWD:/source magland/mldevel_publish npm
    on:
      tags: true
    skip_cleanup: true
