language: node_js
services:
- docker
os:
- linux
node_js:
- node
install:
- npm install
deploy:
  - provider: script
    script: ./devel/travis_deploy.sh
    on:
      tags: true
    skip_cleanup: true
