language: node_js
services:
- docker
os:
- linux
node_js:
- node
env:
- GLOBAL_INSTALL_FLAG=--global
- GLOBAL_INSTALL_FLAG=
install:
- npm install $GLOBAL_INSTALL_FLAG
deploy:
  - provider: script
    script: ./devel/travis_deploy.sh
    skip_cleanup: true
