language: node_js
services:
- docker
os:
- linux
node_js:
- node
install:
- npm install
deploy:
- provider: script
  script: "./devel/travis_deploy.sh"
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: fYplxvhMQyhthoQv0qUkVpStn91adlVD61m43KDqGpNN9VhUUd+8X6uCDdh+iaAyVnJjTifvYOfXdd92+9CVhvyu2SrBXE2IZaHgMJgFQbm2/9vOMv0EhePSeh0otFUYZZ1TGm1Bzl8skm0gLjVGSWEz6eOXzAgl+is/8VXbMPrbzNvGfiiT6m8bVQGpOtrsnv3dj8WUOUASxBDKix86k++1JsH1Myl+5HJ3aN7BQ5z2Ip9FGSKveznIzGDpmXZkYuJmRgPwbNk8Evi0D3xpJik7FPDnDj19Cjph1slbmRXyjO2EyLuBFcZ24tdoVTAxOl2qFWRYxgjQ6Y/Ukw79zymMT3DTPv4y7gb5PLBjM6zjqU1ygJJZoNTkep1TA+aCNlYCGAIG22mnS3SL5Lj7O3o3ynGDqbCUW+SVdOI9D2VQ4UBvVGdYxezelKEgBXU2L8x7rzubknUpi/2udL8jdUf9UmD11v9jYU22vO3GpNtSHZlnYkHLrZ4X5wFlOoE2tsbqn7Q0kay8WRH/2zIch1Tem5stX+MvNfUKUtA84ZZlTtDgLMYQ+bKVtMJcmh3hUYATMyF7Aq48zkXD9sZoFwCnq4IQ8V+ypL4c3n5wbjDPpG6IE1fSHfTZGgOsnguP+qFosvNEV87bcdy/gV4zA+LVo1sytFnPfNS5BdlA32o=
  - secure: mvn1q8q3+QMEC9Vepl/ehS1pq/75EMvesaYbppc9mtqVGAkh8j1GrKF2nXTewT0B5cSVlb1tZMiuiaQBFzGULiLqG/GAYnhhagvaXNaE6RijivmA+nwevylU5Bs79YRRPjC4Jntq31PMDeetgGnou7kp7Fx5/w3ahF+kV8ipAmsk8Frm6mZOCQbbJ3Nl/aTRqfeeSrAMB+9ki2+sIs1noxykCoy0Wyc+XYvtXwtjQDhe+sM/sCIz+QEKZf7G/tmj5WJthSxpRXfgdamceu5ILyksqqd3ITMlF3vGOapecHpJmhxkakAbTPZ3KB7WSEXQI7eKrZKV+POnHrnb2j1Wf8oc/unYlQ4kF6wdvnDrKNP2D/buFRvrYW9Q5WOxeYqQruZwdmH8rR6J7bOd6FmeocW1bZ6bbKWLUyBZBs0AyRZzY8VADvvVJq4y0peeictANUWOOj5DogbLxVCXU6JZJMFbw7D+YwllzE0YKEm5bRw1sM2eotZ0TVFrW/CCoVutcx3QM5ijEHzQUCeGT82Dy2PSOAk9FaiEj0wXufUy5NifEGVSwbSXNK07z5wSoao12FfEdlhXzW5Z0Ya5sk6pYAmGqiyvcV99WiD2yl4hjU6XLa+W1ZPuywf++m9cVnHj4X7nqImYHQAuy/yDRQysE3+9J/Qjq0ttY7q3Oy09+Sk=
# Add the encrypted deploy keys like this:
# travis encrypt NPM_TOKEN=[fill-in-secret] -a
# travis encrypt ANACONDA_API_TOKEN=[fill-in-secret] -a